# Adaptado do workshop-template https://github.com/evanwill/workshop-template
# Um template Jekyll template para um website para oficinas, desenvolvido para github-pages,
# baseado no tema Minima theme https://github.com/jekyll/minima

# Notes:
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Oficina de Produção Textual Acadêmica e Diagramação com LaTeX - UFOP
description: "Curso introdutório 101 (Beabá) de LaTeX para escrita acadêmcia."
keywords: "latex, latex-ufop, template-abnt-ufop"

# author settings for cc-by
author: prof. Dr. Danny A. V. Tonidandel
pub_year: 2022
github_username: tonidandel
# add the full url for the github repository
repo: "https://github.com/tonidandel/oficina-latex"

# urls
# your gh-pages url: https://username.github.io
url: https://tonidandel.github.io/
# your repository name: /ghpages-test-site
baseurl: /oficina-latex
# analytics if desired (and use environment variable on build command)
#google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
